image: tmaier/compose:latest

stages:
    - tests

variables:
    TARGET: test

services:
  - docker:dind

before_script:
  - docker info
  - docker-compose --version

test-web:
  stage: tests
  script:
    - docker-compose up --build web