image: tmaier/docker-compose:latest

stages:
  - tests

variables:
  TARGET: test
  COMPOSE_DOCKER_CLI_BUILD: 1
  DOCKER_BUILDKIT: 1

services:
  - docker:dind

before_script:
  - docker info
  - docker-compose --version

test-web:
  stage: tests
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  script:
    - echo ${TARGET}
    - docker-compose up --exit-code-from web --abort-on-container-exit --build web
  artifacts:
    reports:
      cobertura: Website/coverage/cobertura-coverage.xml
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
