version: '3.9'
services:
  # Website
  web:
    build:
      context: ./Frontend
      target: dev
    command: npm run start:dev
    restart: always
    working_dir: /usr/app
    volumes:
      - ./Frontend/:/usr/app/
      - /usr/app/node_modules
    environment:
      - NODE_ENV=development
      - DEBUG=nodejs-docker-express:*
    ports:
      - "3001:3001"
    depends_on:
      - db
    networks:
      backend-db:
        ipv4_address: 10.0.0.2
  # Postgres Database
  db:
    container_name: database
    image: postgres:latest
    build:
      context: ./Database
    environment:
      # TODO: Get values from environment variables
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: osteams
    ports:
      - '5432:5432'
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      backend-db:
        ipv4_address: 10.0.0.3
      db-pgadmin4:
        ipv4_address: 10.0.1.3
  # PGAdmin4 Panel
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      # TODO: Get values from environment variables
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./data/pgadmin-data:/var/lib/pgadmin
    networks:
      db-pgadmin4:
        ipv4_address: 10.0.1.4
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    depends_on:
      - db

volumes:
  postgres-db:

networks:
  backend-db:
    ipam:
      driver: default
      config:
        - subnet: "10.0.0.0/24"
          gateway: 10.0.0.1
  db-pgadmin4:
    ipam:
      driver: default
      config:
        - subnet: "10.0.1.0/24"
          gateway: 10.0.1.1
