version: '3.9'
services:
  # Website
  web:
    build:
      context: ./Website
      target: ${TARGET:-development}
    restart: "no"
    working_dir: /usr/app
    volumes:
      - ./Website/:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3001:3001"
    depends_on:
      - db
    networks:
      - backend-db
  # Postgres Database
  db:
    container_name: database
    build:
      context: ./Database
      target: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-osteams}
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    # TODO: Volume currently disabled to make it volatile. Uncomment to make it persistent.
    #volumes:
    #  - postgres-db:/var/lib/postgresql/data
    networks:
      - backend-db
      - db-pgadmin4
      - db-backup
  # DB Backup
  db-backup:
    container_name: db-backup
    build:
      context: ./Cron
      target: cron
    command: crond -f -l 8
    depends_on:
      - db
    networks:
      - db-backup
    volumes:
      - db-backup:/var/opt/
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-root}
      PGADMIN_CONFIG_SERVER_MODE: ${PGADMIN_CONFIG_SERVER_MODE:-False}
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - db-pgadmin4
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    depends_on:
      - db

volumes:
  postgres-db:
  pgadmin:
  db-backup:

networks:
  backend-db:
    ipam:
      driver: default
  db-pgadmin4:
    ipam:
      driver: default
  db-backup:
    ipam:
      driver: default
