version: '3.9'
services:
  # Website
  web:
    build:
      context: ./Frontend
    command: node index.js
    restart: always
    working_dir: /usr/app
    ports:
      - "3001:3001"
    depends_on:
      - db
    networks:
      internal-network:
        ipv4_address: 192.168.0.2
  # Postgres Database
  db:
    container_name: database
    image: postgres:latest
    build:
      context: ./Database
    environment:
      # TODO: Get values from environment variables
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: osteams
    ports:
      - '5432:5432'
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      internal-network:
        ipv4_address: 192.168.0.3
  # PGAdmin4 Panel
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      # TODO: Get values from environment variables
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./data/pgadmin-data:/var/lib/pgadmin
    networks:
      internal-network:
        ipv4_address: 192.168.0.4
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    depends_on:
      - db

volumes:
  postgres-db:

networks:
  internal-network:
    ipam:
      driver: default
      config:
        - subnet: "192.168.0.0/24"
          gateway: 192.168.0.1
