version: '3.9'
services:
  # Traefik routing
  traefik:
    build:
      context: Traefik
    container_name: traefik
    hostname: traefik
    networks:
      - traefik_net
    command:
      - --log.level=${TRAEFIK_LOG_LEVEL:-INFO}
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /ostchat/traefik/letsencrypt/acme.json:/letsencrypt/acme.json:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
  # Website
  web:
    build:
      context: ./Website
      dockerfile: dockerfile
      target: ${TARGET:-development}
    environment:
      - DB_DNS_NAME=${DB_DNS_NAME:-database}
      - DB_DATABASE=${DB_DATABASE:-osteams}
      - DB_PORT=${DB_PORT:-5432}
      - DB_BACKEND_USER=${DB_BACKEND_USER:-backend}
      - DB_BACKEND_PASSWORD=${DB_BACKEND_PASSWORD:-password}

      - EMAIL_PASSWORD=${EMAIL_PASSWORD:-)L%&3Lm>7u;pDN<S}
      - EMAIL_SERVICE=${EMAIL_SERVICE:-Hotmail}
      - EMAIL_ADDRESS=${EMAIL_ADDRESS:-osteams@hotmail.com}
    restart: "no"
    extends:
      file: ./Website/docker-compose.web.yaml
      service: "web-${TARGET:-development}"
    working_dir: /usr/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`${DOMAIN:-localhost}`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.docker.network=traefik_net"
      - "traefik.http.services.web.loadBalancer.sticky.cookie=true"
    volumes:
      - /usr/app/node_modules
    ports:
      - "3001:3001"
    depends_on:
      - db
    networks:
      - traefik_net
      - backend-db
  # Postgres Database
  db:
    container_name: ${DB_DNS_NAME:-database}
    build:
      context: ./Database
      dockerfile: dockerfile
      target: postgres-${TARGET:-development}
      args:
        - DB_BACKEND_PASSWORD=${DB_BACKEND_PASSWORD:-password}
        - DB_BACKEND_USER=${DB_BACKEND_USER:-backend}
        - DB_PORT=${DB_PORT:-5432}
        - DB_DATABASE=${DB_DATABASE:-osteams}
    environment:
      POSTGRES_USER: ${DB_ADMIN_USER:-admin}
      POSTGRES_PASSWORD: ${DB_ADMIN_PASSWORD:-password}
      POSTGRES_DB: ${DB_DATABASE:-osteams}
    ports:
      - '${DB_PORT:-5432}:5432'
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - backend-db
      - db-pgadmin4
      - db-backup
  # DB Backup
  db-backup:
    container_name: db-backup
    build:
      context: ./Cron
      dockerfile: dockerfile
      target: cron
      args:
        - DB_ADMIN_USER=${DB_ADMIN_USER:-admin}
        - DB_ADMIN_PASSWORD=${DB_ADMIN_PASSWORD:-password}
        - DB_DATABASE=${DB_DATABASE:-osteams}
        - DB_PORT=${DB_PORT:-5432}
        - DB_DNS_NAME=${DB_DNS_NAME:-database}
    command: crond -f -l 8
    depends_on:
      - db
    networks:
      - db-backup
    volumes:
      - db-backup:/var/opt/
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-root}
      PGADMIN_CONFIG_SERVER_MODE: ${PGADMIN_CONFIG_SERVER_MODE:-False}
    labels:
      - traefik.enable=true
      - traefik.http.routers.pgadmin.rule=Host(`pgadmin.${DOMAIN:-localhost}`)
      - "traefik.http.routers.pgadmin.entrypoints=websecure"
      - traefik.docker.network=traefik_net
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - traefik_net
      - db-pgadmin4
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    depends_on:
      - db

volumes:
  postgres-db:
    external: false
  pgadmin:
  db-backup:
  letsencrypt:


networks:
  backend-db:
    ipam:
      driver: default
  db-pgadmin4:
    ipam:
      driver: default
  db-backup:
    ipam:
      driver: default
  traefik_net:
    name: traefik_net
    ipam:
      driver: default
