# DAMN YOU UN-DEBUGGABLE SCRIPT FILES
# https://github.com/DoTheEvo/Traefik-v2-examples
# Complete guide: https://traefik.io/blog/traefik-2-tls-101-23b4fbee81f1/

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443
    http:
      tls:
        certResolver: myresolver

certificatesResolvers:
  myresolver:
    acme:
      email: dominic.walther@ost.ch
      storage: /letsencrypt/acme.json
      tlsChallenge: {}

api:
  insecure: true
  dashboard: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
