FROM postgres:14-alpine3.15 AS postgres-production

RUN apk update && apk upgrade
EXPOSE 5432
COPY schemas/*.sql /docker-entrypoint-initdb.d/
COPY production/*.sql /docker-entrypoint-initdb.d/

FROM postgres-production as postgres-development
COPY tests/*.sql /docker-entrypoint-initdb.d/

FROM postgres-production as postgres-test
COPY tests/*.sql /docker-entrypoint-initdb.d/
